# Generated by Django 4.1.3 on 2022-11-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=512)),
                ("url", models.URLField()),
                ("current_price", models.FloatField(blank=True)),
                ("old_current_price", models.FloatField(default=0)),
                ("current_price_difference", models.FloatField(default=0)),
                ("original_price", models.FloatField(default=0)),
                ("seller", models.CharField(max_length=500)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
